---
- name: Definindo TimeZone como America/Sao_Paulo
  timezone:
    name: America/Sao_Paulo

- name: Criando usuario splunk
  user:
    name: splunk
    comment: splunk user

- name: Download instalador para máquina local
  local_action:
    module: get_url
    url: "{{splunk_url_download}}"
    dest: ../pacotes/
  register: splunk_pacote

- name: Copia instalador da máquina local
  copy:
    src: "../pacotes/{{splunk_pacote.dest|basename}}"
    dest: /tmp/

- name: Instalando Splunk
  dnf:
    name: "/tmp/{{splunk_pacote.dest|basename}}"
    disable_gpg_check: yes
    state: installed

- name: Criando env_var SPLUNK_HOME
  lineinfile:
    dest: /etc/profile.d/splunk_var.sh
    line: "export SPLUNK_HOME=/opt/splunk/"
    create: yes
    state: present

- name: Adicionando os comandos do splunk ao PATH
  lineinfile:
    dest: /etc/profile.d/custom_path.sh
    line: "export PATH=$PATH:/opt/splunk/bin"
    create: yes
    state: present

- name: Configurando senha de Admin
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd {{splunk_pass_admin}}
  become_user: splunk

- name: habilitando listen 9997
  shell: /opt/splunk/bin/splunk enable listen 9997 -auth admin:{{splunk_pass_admin}}
  become_user: splunk

- name: Parando processo do splunk
  shell: /opt/splunk/bin/splunk stop
  become_user: splunk

- name: Criando unit service do Splunk
  shell: /opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk -group splunk

- name: Ajustando unit Splunkd
  lineinfile:
    path: /etc/systemd/system/Splunkd.service
    regexp: "ExecStartPost"
    line: "ExecStartPre"
    state: present

- name: Ajustando permissão no dir /opt/splunk para o user splunk
  file:
    dest: /opt/splunk
    owner: splunk
    group: splunk
    mode: u+rw
    recurse: yes

- name: Iniciando serviço Splunkd
  systemd:
    daemon_reload: yes
    name: Splunkd
    state: restarted
    enabled: yes
