---
- name: Verifica se o NGINX está instalado
  ansible.builtin.stat:
    path: /sbin/nginx
  register: nginx_bin

- name: Instala NGINX caso não esteja instalado
  include_tasks: install.yml
  when: not nginx_bin.stat.exists

- name: Configura NGINX
  include_tasks: configure.yml
