# -*- mode: ruby -*-
# vi: set ft=ruby  :

#Variavéis 
IMAGE_NAME = "almalinux/9"
SPLUNK_MEMORY=1024
SPLUNK_VCPU=2
SPLUNK_PASS_ADMIN="splunk@123"
NETWORK_PREFIX="192.168.165"
VM_GROUP_NAME="SPLUNK"
SPLUNK_URL_DOWNLOAD="url"
INDEXER_NODES=2
SEARCH_NODES=3
SPLUNK_SECRET_CLUSTER_INDEXER="splunk@123"
SPLUNK_NAME_CLUSTER_INDEXER="idx0"
SPLUNK_REPLICATION_FACTOR=2
SPLUNK_SEARCH_FACTOR=2

Vagrant.configure("2") do |config|
    #Cluster Master Indexers
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "#{NETWORK_PREFIX}.10"
        master.vm.hostname = "master"
        master.vm.provider :virtualbox do |vb|
            vb.name = "master"
            vb.memory = SPLUNK_MEMORY
            vb.cpus = SPLUNK_VCPU
            vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
        end        
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "../ansible/main.yml"
            ansible.groups = {
                "splunk_master" => ["master"],
                "splunk-master:vars" => {"master" => true }
            }
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python",
                splunk_pass_admin: SPLUNK_PASS_ADMIN,
                splunk_url_download: SPLUNK_URL_DOWNLOAD
            }
        end
    end
    #indexers
    (1..INDEXER_NODES).each do |i|
        config.vm.define "indexer-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.#{i + 10}"
            node.vm.hostname = "indexer-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.name = "indexer-#{i}"
                vb.memory = SPLUNK_MEMORY
                vb.cpus = SPLUNK_VCPU
                vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
            end                  
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../ansible/main.yml"
                ansible.groups = {
                    "indexers" => ["indexer-[1:#{INDEXER_NODES}]"]
                }                
                ansible.extra_vars = {
                    ansible_python_interpreter: "/usr/bin/python",
                    splunk_pass_admin: SPLUNK_PASS_ADMIN,
                    splunk_name_cluster_indexer: SPLUNK_NAME_CLUSTER_INDEXER,
                    splunk_secret_cluster_indexer: SPLUNK_SECRET_CLUSTER_INDEXER,
                    splunk_replication_factor: SPLUNK_REPLICATION_FACTOR,
                    splunk_search_factor: SPLUNK_SEARCH_FACTOR,
                    splunk_master_ip: "#{NETWORK_PREFIX}.10"
                }
            end
        end
    end
    # Search Heads
    (1..SEARCH_NODES).each do |i|
        config.vm.define "search-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.#{i + 20}"
            node.vm.hostname = "search-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.name = "search-#{i}"
                vb.memory = SPLUNK_MEMORY
                vb.cpus = SPLUNK_VCPU
                vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
            end                  
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../ansible/main.yml"
                ansible.groups = {
                    "searchs" => ["search-[1:#{SEARCH_NODES}]"]
                }                
                ansible.extra_vars = {
                    ansible_python_interpreter: "/usr/bin/python",
                    splunk_master_ip: "#{NETWORK_PREFIX}.10",
                    splunk_pass_admin: SPLUNK_PASS_ADMIN,
                    splunk_secret_cluster_indexer: SPLUNK_SECRET_CLUSTER_INDEXER
                }
            end
        end
    end
    # Proxy para search Heads
    config.vm.define "nginx" do |nginx|
        nginx.vm.box = IMAGE_NAME
        nginx.vm.network "private_network", ip: "#{NETWORK_PREFIX}.30"
        nginx.vm.hostname = "nginx"
        nginx.vm.provider :virtualbox do |vb|
            vb.name = "nginx"
            vb.memory = SPLUNK_MEMORY
            vb.cpus = SPLUNK_VCPU
            vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
        end        
        nginx.vm.provision "ansible" do |ansible|
            ansible.playbook = "../ansible/main.yml"
            ansible.groups = {
                "ngnix" => ["nginx"],
                "searchs" => SEARCH_NODES,
                "network_prefix" => NETWORK_PREFIX
            }
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python"
            }
        end
    end
end